### ISSUE TITLE
Problems on Edge browser

### ISSUE THREAD

**Issue by frituc** [haukex/de-en-dict#22]
[Report from a former Beolingus user]

Unfortunately, I get an error message when I open up the page with Edge (version 126.0.2592.102):

The dictionary failed to load! Please make sure you're using a modern browser and have a working Internet connection. Reload this page to try again. It is also possible that the dictionary server is offline - try [this link](https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/) to check.

I get this error message when accessing dict.zero-g.net on network computers with download restrictions.

frituc: Hm, if Edge may be configured by policy to accept or reject .gz files, then we probalbly have no chance …

**Comment by haukex** [comment]
Hi, thanks for the report.

> I get this error message when accessing dict.zero-g.net on network computers with download restrictions.

Could you try opening the indicated link (<https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/>) and seeing if you can download the file `de-en.txt.gz`, do you get an error message or does that work? If you get an error, could you try downloading the file `de-en.txt.zip` instead and seeing if that works or not, and report back here?

Downloading the Zip version of the dictionary could maybe be a potential fix in this situation; the two files appear to be very similar in size.

Of course you could also ask your network administrator for access to that particular file.

*Update:* Also, please try updating your version of Edge to the latest version - even though the version you're using is fairly recent, it can't hurt to try.

**Comment by haukex** [comment]
I've now added detailed output to the "The dictionary failed to load!" error message, if you could post that here that might be useful. Note that you may need to clear your browser's cache and delete saved data for "zero-g.net" to force a reload of the latest version of the application.

**Comment by haukex** [comment]
I researched a bit more and unfortunately, Zip is not supported natively in JavaScript (only gzip and deflate). It would therefore make sense if you could check if updating the browser and the app or talking to your network administrators would be an easier solution.
