### ISSUE TITLE
Display in Edge

### ISSUE THREAD

**Issue by frituc** [haukex/de-en-dict#23]
[Report from a former Beolingus user]

With the Edge browser, which I use a lot, the two language columns are usually not displayed completely in width and when scrolling down, the display often shifts horizontally, so that I have to move the cursor letter by letter into the area outside the screen display. A horizontal scroll bar at the bottom would be an improvement. 

![Bildschirmseite dict zero-g net-1](https://github.com/user-attachments/assets/f7a3a14c-532d-406a-8cdc-2e2fdd4bea4b)

**Comment by haukex** [comment]
Hi, thanks for the report.

Unfortunately, I was unable to reproduce this on Edge 127.0.2651.105 on Windows 10, including when I changed some of the display settings in the browser.

Could you please verify that you are using the latest version of Edge and report back what version you're using? Also, could you check and report back whether you have changed any display settings in the browser (like font size), or if you have any plug-ins installed in the browser that could affect the page display?

You can also try forcing the latest version of the page to load by clearing your browser's cache and clearing the saved data for "zero-g.net".
