### ISSUE TITLE
Sometimes get an error on first load in Firefox

### ISSUE THREAD

**Issue by haukex** [haukex/de-en-dict#32]
In Firefox, after clearing the cache and re-loading the dictionary for the first time, I sometimes get a "The dictionary failed to load!" error:

```
$Id: 214f5c345c91b2dcccfb13fcd3e470404fbe7221 $
TypeError: The input data is corrupted: incorrect header check
```
or
```
$Id: 214f5c345c91b2dcccfb13fcd3e470404fbe7221 $
TypeError: The input is ended without reaching the stream end
```

and the console shows:
```
https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/de-en.txt.gz cors 200 OK [worker.8ab956e8.js:1:3751](https://dict.zero-g.net/worker.8ab956e8.js)
ProgressTransformer expected 8682926 but got 0
```

A reload fixes the issue.

I suspect a bug in Firefox rather than the app, but I could take a closer look at it.

*Edit:* According to the network trace, Firefox is sending `Range: bytes=1542415-` and `If-Range: "847dae-62305d44eb300"` headers and the server is responding with `206 Partial Content`, could that be the cause?

*Edit 2:* I'm now also sometimes getting errors in Firefox that the tab has crashed, which feels to me to confirm a bug in Firefox. Still looking for a workaround.

**Comment by frituc** [comment]
The same here with Firefox 128.3.1esr
In private tab it doesn't work after reloading …

**Comment by frituc** [comment]
Ok, after F12 and disabling cache it worked.

**Comment by haukex** [comment]
Thanks, unfortunately I'm still not sure why this is happening. I'm still guessing it's maybe a bug in Firefox for HTTP requests sent from Web Workers or something. It seems that usually a simple reload fixes the problem (and it seems to only happen after clearing the saved website data).

**Comment by haukex** [comment]
I just implemented #35, which means that dictionary updates will now be retried when the page is reloaded, so at the very least the current workaround of just reloading the page in Firefox should work for updates too...

*Edit:* I should probably also implement a message "background update failed" instead of the status bar just showing "(Updating in background...)" forever. *Edit 2:* Now did that in a70a9f5ac84af662e1127ce1f18415490b51ea3c.

**Comment by haukex** [comment]
Interestingly, since I implemented 6c2f957602ed39d423170ccbeff0e0159058869c and 812686d99bcbe4ab8feb44cc573fedbd2346be77, I haven't seen the error anymore, so it seems my guesses may have worked around the problem. I will monitor this for a while, and if I don't see the error anymore, I can assume that one or both of those commits fixed it.

**Comment by haukex** [comment]
I haven't seen any more Firefox crashes since the above, so I hope this is fixed.

**Comment by christophfriedrich** [comment]
This just happened to me using Firefox 139.0.4 on Windows 11. Opened the site (using my usual `beo searchterm` shortcut forwarding me to https://dict.zero-g.net/#q=lizenz) and got this:

![Image](https://github.com/user-attachments/assets/8a8df5de-63a3-4746-93b7-32d6f0094600)

Console output:

![Image](https://github.com/user-attachments/assets/a5d06a77-0576-4009-9a7f-aadf1053af8f)

Hitting F5 resolved the issue.

![Image](https://github.com/user-attachments/assets/00a3fc0b-2489-47d2-85a8-9888a3de0717)

**Comment by haukex** [comment]
Thanks for the report - was this a one-time thing or are you able to reproduce it? Is this a PC where you use the dictionary often (because if not, it might be possible there was still an older version of the app in the cache)? *Edit:* More specifically, reproducing it would probably mean clearing all saved data for `dict.zero-g.net` and reloading the page, maybe doing this a couple of times, to see if you can still get the error to occur.

**Comment by haukex** [comment]
@christophfriedrich Have you had any luck reproducing this? Or perhaps it was only a one-time thing?

**Comment by christophfriedrich** [comment]
This happened to me again today in Firefox 148 on Mac:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:148.0) Gecko/20100101 Firefox/148.0
$Commit: d2057c3 $
TypeError: The input is ended without reaching the stream end
```

The URL I opened was https://dict.zero-g.net/#q=pr%C3%A4zisieren via my URL bar shortcut.

Console output:
```
updateState Init to Init dict.zero-g.net:1:41984
updateState Init to AwaitingDict dict.zero-g.net:1:41984
SW register ok
ServiceWorkerRegistration { installing: null, waiting: null, active: ServiceWorker, navigationPreload: NavigationPreloadManager, scope: "https://dict.zero-g.net/", updateViaCache: "imports", onupdatefound: null, pushManager: PushManager, cookies: CookieStoreManager } dict.zero-g.net:1:40527
SW: fetch: Intercepting GET https://dict.zero-g.net/favicon.25230955.ico dict.zero-g.net:1:40673
SW: fetch: Intercepting GET https://dict.zero-g.net/worker.d58dcf4f.js dict.zero-g.net:1:40673
updateState AwaitingDict to AwaitingDict dict.zero-g.net:1:41984
The dictionary data is in the cache, using that first, and will check for update in background. worker.d58dcf4f.js:1:4873
ProgressTransformer expected 9022587 but got 5505024 worker.d58dcf4f.js:1:2477
updateState AwaitingDict to Error dict.zero-g.net:1:41984
SW: fetch: NOT Intercepting GET https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/sha256sums.txt dict.zero-g.net:1:40673
The dict version information has changed. worker.d58dcf4f.js:1:3075
Dictionary needs update, starting background update. worker.d58dcf4f.js:1:5030
SW: fetch: NOT Intercepting GET https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/de-en.txt.gz dict.zero-g.net:1:40673
https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/de-en.txt.gz cors 200 OK worker.d58dcf4f.js:1:4781
Decompressed 27550363 characters. worker.d58dcf4f.js:1:2744
Decoded 205907 dictionary lines with 411972 entries. worker.d58dcf4f.js:1:4323
Stats line reports 1054743 1:1 translations. worker.d58dcf4f.js:1:4607
updateState Error to Error dict.zero-g.net:1:41984
Saved the new dict version information. worker.d58dcf4f.js:1:2892
```

As screenshot:

<img width="1680" height="877" alt="Image" src="https://github.com/user-attachments/assets/7a27b2a7-3ed0-45e6-8ea1-792ed16dc45e" />

Opening the same URL again in a new tab worked perfectly fine.

**Comment by christophfriedrich** [comment]
So it seems to be NOT a one-time thing, but still rather rare and I wasn't able to reproduce it on purpose. In principle, this is a browser where I use the dict often, but I just came back from vacation today, so hadn't used it in a while (last time on 26th March). Sorry for not responding to your questions for so long...
