### ISSUE TITLE
Zusätzlicher Query-Parameter

### ISSUE THREAD

**Issue by Tekl** [haukex/de-en-dict#7]
Ich möchte gerne aus meinem [Beolingus Lexikon-Plug-in](https://tekl.de/lexikon-plug-ins/beolingus-deutsch-englisch-lexikon-plugin) für macOS direkt auf die Suche verlinken. Leider funktionieren Links aus der Lexikon-App nicht, sobald sie ein # einhalten. Deshalb wäre es toll, wenn nicht nur <https://dict.zero-g.net/#q=Beo> funktionieren würden, sondern auch <https://dict.zero-g.net/?q=Beo>. Das könnte dann ja einfach auf den Hash umleiten.

**Comment by haukex** [comment]
Danke für die Idee, ist erledigt!

**Comment by Tekl** [comment]
Danke für die schnelle Umsetzung.
